CREATE TABLE [dbo].[ASSETS]
(
    [ASSETID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [ASSETREF] VARCHAR(13) NULL,
    [PROJECTID] INT NULL,
    [LATITUDE] DECIMAL(10,8) NULL,
    [LONGITUDE] DECIMAL(11,8) NULL,
    [ISDELETED] BIT NOT NULL DEFAULT 0,  -- Soft delete flag
    FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[PROJECT]([PROJECTID]),
    INDEX IX_ASSETREF_PROJECTID UNIQUE (ASSETREF, PROJECTID)  -- Composite unique index
);
