CREATE TABLE [dbo].[COMPANY]
(
	[COMPANYID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [COMPANYNAME] VARCHAR(100) NULL, 
    [ADDRESS] VARCHAR(100) NULL, 
    [ZIPCODE] VARCHAR(20) NULL, 
    [PROVINCE] VARCHAR(50) NULL,
    [LOGOURL] NVARCHAR(MAX) NULL,
    [EMAIL] VARCHAR(100) NULL,
    [CONTACTNUMBER] VARCHAR(50) NULL
)
