CREATE TABLE [dbo].[INSPECTIONS]
(
	[INSPECTIONCHECKID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [INSPECTIONTYPEID] INT NULL, 
    [CONTENT] VARCHAR(MAX) NULL, 
    [CLASSID] INT NULL,
    [ISDELETED] BIT NOT NULL DEFAULT 0,  -- Soft delete flag
    FOREIGN KEY ([INSPECTIONTYPEID]) REFERENCES [dbo].[INSPECTIONTYPE]([INSPECTIONTYPEID]),
    FOREIGN KEY ([CLASSID]) REFERENCES [dbo].[INSPECTIONCLASS]([CLASSID])
)
