CREATE TABLE [dbo].[INSPECTIONTYPE]
(
	[INSPECTIONTYPEID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [INSPECTIONTYPENAME] VARCHAR(50) NULL, 
    [DESCRIPTION] VARCHAR(250) NULL, 
    [PROJECTID] INT NULL,
    FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[PROJECT]([PROJECTID])
)
