CREATE TABLE [dbo].[INSPECTIONIMAGE]
(
	IMAGEID INT PRIMARY KEY IDENTITY,
    HEADERID INT,
    IMAGEURL NVARCHAR(MAX),
    UPLOADDATE DATETIME,
    FOREIGN KEY ([HEADERID]) REFERENCES [dbo].[INSPECTIONHEADER]([HEADERID])
)
