CREATE TABLE [dbo].[INSPECTIONLINE]
(
	[LINEID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [HEADERID] INT NULL, 
    [CHECKID] INT NULL, 
    [RESULTBOOLEAN] BIT NULL, 
    [RESULTTEXT] VARCHAR(MAX) NULL, 
    [RESULTDROPDOWN] INT NULL,
    [ISDELETED] BIT NOT NULL DEFAULT 0,  -- Soft delete flag
    FOREIGN KEY ([HEADERID]) REFERENCES [dbo].[INSPECTIONHEADER]([HEADERID])
)
