CREATE TABLE [dbo].[INSPECTIONHEADER]
(
    [HEADERID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [COMPANYCODE] INT NULL, 
    [PROJECTID] INT NULL, 
    [USERID] INT NULL,
    [INSPECTIONTYPEID] INT NULL, 
    [ASSETID] UNIQUEIDENTIFIER NOT NULL, -- Reference to an asset
    [CREATIONDATE] DATETIME NULL, 
    [LATITUDE] DECIMAL(10,8) NULL,
    [LONGITUDE] DECIMAL(11,8) NULL, 
    [PASS] BIT NULL, 
    [COMMENT] VARCHAR(MAX) NULL,
    FOREIGN KEY ([COMPANYCODE]) REFERENCES [dbo].[COMPANY]([COMPANYID]),
    FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[PROJECT]([PROJECTID]),
    FOREIGN KEY ([USERID]) REFERENCES [dbo].[USER]([USERID]),
    FOREIGN KEY ([INSPECTIONTYPEID]) REFERENCES [dbo].[INSPECTIONTYPE]([INSPECTIONTYPEID]),
    FOREIGN KEY ([ASSETID]) REFERENCES [dbo].[ASSETS]([ASSETID])
);
