CREATE TABLE [dbo].[INSPECTIONIMAGE]
(
	IMAGEID INT PRIMARY KEY IDENTITY,
    HEADERID INT,
    IMAGEURL NVARCHAR(MAX),
    UPLOADDATE DATETIME,
    ISDELETED BIT NOT NULL DEFAULT 0,  -- Soft delete flag
    FOREIGN KEY ([HEADERID]) REFERENCES [dbo].[INSPECTIONHEADER]([HEADERID])
)
