CREATE TABLE [dbo].[PROJECT]
(
	[PROJECTID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PROJECTNAME] VARCHAR(50) NULL, 
    [STARTDATE] DATETIME NULL, 
    [ENDDATE] DATETIME NULL, 
    [COMPANYCODE] INT NULL,
    [ISDELETED] BIT NOT NULL DEFAULT 0,  -- Soft delete flag
    FOREIGN KEY ([COMPANYCODE]) REFERENCES [dbo].[COMPANY]([COMPANYID])
)
